### ISSUE TITLE
run the model but get the error, help please!

### ISSUE THREAD

**Issue by kshuc152** [ankonzoid/artificio#1]
Hello! Thanks for your sharing, I get a TyoeError when I run the model, and I do not know how to solve it.
On ubuntu14.04, python3.5.2
Detail as following:
Traceback (most recent call last):
  File "image_rec.py", line 357, in <module>
    main()
  File "image_rec.py", line 204, in main
    MODEL.load_model(dictfn)
  File "/home/naver/line-brain/lixun/cnn-based/image_rec/algo/autoencoders/AE.py", line 137, in load_model
    self.encoder = load_model(encoder_filename)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 240, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip-huypgcah-build/h5py/h5f.c:2117)
OSError: Unable to open file (Unable to open file: name = 'db/models/convae_encoder.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f8d737435f8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 595, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ankonzoid** [comment]
Hi there,

It seems like the encoder is named "ConvAE_encoder.h5" rather than "convAE_encoder.h5". Does changing the name solve the problem? I will have to make these changes tonight and update the repo. Thanks for helping me catch this. Feel free to update me with any other troubles you experience.

**Comment by ankonzoid** [comment]
I have now made the fix of the encoder model filename, and detailed the README.md file to outline the libraries needed to run the code. It should be working fine now (at least it has on my computer). The code should be able to as is with a "python image_rec.py" command. I will close this issue for now, but please let me know if you can't get it running!
